# This workflows parse all existing repos and enforce branch policy

name: Enable protected Branchs everywhere

on:
  # manual
  workflow_dispatch:
  # nightly every day
  schedule:
    - cron: "0 0 * * *"

jobs:
  Enforce:
    env:
      PAT: ${{ secrets.PAT }}
      ORG_NAME: "lgmorandOrg"
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq
           
      - name: List repos
        run: |
            curl -u "lgmorand:$PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/{{env.$ORG_NAME}}/repos | jq '.[].full_name'

      - name: List branchs and status
        run: |
            curl -u "lgmorand:$PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/{{env.$ORG_NAME}}/LG-repository-template/branches | jq '[{"name": .[].name, "protected": .[].protected}]'

      - name: Enable protected branch
        run: | 
           curl -X PATCH -u "lgmorand:$PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/{{env.$ORG_NAME}}/LG-repository-template/branches/main/protection/required_pull_request_reviews -d '{"require_code_owner_reviews":true}'
           
