# This workflows list all repos, their branch and enable it for main branch

name: Enable protected Branchs everywhere

on:
  workflow_dispatch:

jobs:
  Enforce:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq
           
      - name: List repos
        run: |
            curl -u "lgmorand:$PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/lgmorandOrg/repos | jq '.[].full_name'

      - name: List branchs and status
        run: |
            curl -u "lgmorand:$PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lgmorandOrg/LG-repository-template/branches | jq '[{"name": .[].name, "protected": .[].protected}]'

      - name: Enable protected branch
        run: | 
           curl -X PATCH -u "lgmorand:$PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lgmorandOrg/LG-repository-template/branches/main/protection/required_pull_request_reviews -d '{"require_code_owner_reviews":true}'
           
