# This workflows list all repos, their branch and enable it for main branch

name: Enable protected Branchs everywhere

on:
  workflow_dispatch:

jobs:
  Enforce:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: List repos
        run: |
            curl -u "lgmorand:$PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/ORG/repos

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
